# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: stronglytyped/arm-none-eabi-gcc

pipelines:
  default:
    - step:
        script:
          - apt update
          - apt install libffi-dev pkg-config python3 curl -y
          - cd mpy-cross
          - make
          - cd ../ports/stm32
          - make submodules
          - make BOARD=NUCLEO_H743ZI
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"build-NUCLEO_H743ZI/firmware.hex"
